mutation UpdateProduct_picture($data: UpdateProduct_pictureInput!, $updateProductPictureId: Int!) {
  updateProduct_picture(data: $data, id: $updateProductPictureId) {
    id
    thumbnail
    alt
  }
}