services:
  db:
    stop_grace_period: 0s
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      PGUSER: ${DB_USER:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - prodDB:/var/lib/postgresql/data

  backend:
    stop_grace_period: 0s
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY:-changeme}
      NODE_ENV: ${NODE_ENV:-production}
      CORS-ALLOWED-ORIGINS: ${CORS_ALLOWED_ORIGINS:-changeme} 
    depends_on:
      db:
        condition: service_healthy
    build:
      context: backend
      dockerfile: Dockerfile.production
    volumes:
      - ./backend/src:/app/src/

  frontend:
    stop_grace_period: 0s
    env_file: frontend/.env
    build:
      context: frontend
      dockerfile: Dockerfile.production
    volumes:
      - ./frontend/src:/app/src/
      - ./frontend/public:/app/public/

  upload-service:
    stop_grace_period: 0s
    build: 
      context: upload
      dockerfile: Dockerfile
    volumes:
      - ./upload/files:/app/files/

  gateway:
    restart: always
    stop_grace_period: 0s
    build:
      context: gateway
      dockerfile: Dockerfile.production
    ports:
      - ${GATEWAY_PORT:-80}:80
    
volumes:
  prodDB: