query GetAllBooking($limit: Int, $offset: Int) {
  getAllBooking(limit: $limit, offset: $offset) {
    bookings {
      id
      status
      invoice
      bookingDate
      startDate
      endDate
      user {
        id
        name
        firstname
        address
        postcode
        city
        phone
      }
      agency {
        id
        name
      }
      bookingItem {
        id
        endDate
        startDate
        status
      }
    }
    total
  }
}
