query GetAllBooking($offset: Int, $limit: Int, $userId: Int, $agencyId: Int) {
  getAllBooking(offset: $offset, limit: $limit, userId: $userId, agencyId: $agencyId) {
    bookings {
      id
      status
      invoice
      bookingDate
      startDate
      endDate
      user {
        id
        name
        firstname
        address
        postcode
        city
        phone
      }
      agency {
        id
        name
      }
      bookingItem {
        id
        endDate
        startDate
        status
      }
    }
    total
  }
}
