query GetBookingById($bookingId: Int!) {
  getBookingById(bookingId: $bookingId) {
    id
    status
    invoice
    bookingDate
    startDate
    endDate
    user {
      address
      city
      country
      email
      firstname
      name
      phone
      postcode
    }
    agency {
      address
      city
      country
      email
      name
      phone
      postcode
    }
  }
}