query GetBookingsByUserId($userId: Int!, $offset: Int, $limit: Int) {
  getBookingsByUserId(userId: $userId, offset: $offset, limit: $limit) {
    bookings {
      agency {
        id
        name
        email
        phone
        city
      }
      bookingDate
      endDate
      id
      invoice
      startDate
      status
    }
    total
  }
}