mutation UpdateCategory($data: UpdateCategoryInput!, $categoryId: Int!) {
  updateCategory(data: $data, categoryId: $categoryId) {
    id
    name
    thumbnail
    parentCategory {
      id
    }
  }
}
