query GetAllReviews($productId: Float) {
    getAllReviews(productId: $productId) {
        comment
        id
        rate
        createdAt
        edited
        user {
            id
            avatar
            firstname
            name
        }
    }
}
