query GetReviewsByUserId($userId: Int!, $productId: Float) {
    getReviewsByUserId(userId: $userId, productId: $productId) {
        id
        createdAt
        comment
        rate
        edited
    }
}