query GetReviewsByUserId($userId: Int!, $productId: Int!) {
    getReviewsByUserId(userId: $userId, productId: $productId) {
        id
        createdAt
        comment
        rate
        edited
    }
}