services:
  testDB:
    image: postgres:15-alpine
    restart: always
    stop_grace_period: 0s
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 2s
      retries: 30
    tmpfs: /var/lib/postgresql
    ports:
      - 5432:5432

  backend:
    stop_grace_period: 0s
    env_file:
      - ./.env
    build: ../backend
    ports:
      - 4000:4000
    volumes:
      - ../backend/src:/app/src
    environment:
      DB_HOST: testDB
      KVSTORE_HOST: ${KVSTORE_HOST:-kvStore}
    healthcheck:
      test: "nc -z localhost 4000 || exit 1"
      interval: 1s
      timeout: 2s
      retries: 30
      start_period: 10s
    depends_on:
      testDB:
        condition: service_healthy

  client:
    stop_grace_period: 0s
    build: "../frontend"
    environment:
      - NEXT_PUBLIC_GRAPHQL_API_URL=http://localhost:4000
    ports:
      - 3000:3000
    volumes:
      - ../frontend/src:/app/src
    depends_on:
      backend:
        condition: service_healthy
