export const productStocks = [
  {
    id: 1,
    agency: "Paris",
    quantity: 10,
  },
  {
    id: 2,
    agency: "Marseille",
    quantity: 5,
  },
  {
    id: 3,
    agency: "Lyon",
    quantity: 8,
  },
  {
    id: 4,
    agency: "Toulouse",
    quantity: 3,
  },
  {
    id: 5,
    agency: "Nice",
    quantity: 7,
  },
  {
    id: 6,
    agency: "Nantes",
    quantity: 4,
  },
  {
    id: 7,
    agency: "Strasbourg",
    quantity: 6,
  },
  {
    id: 8,
    agency: "Montpellier",
    quantity: 2,
  },
  {
    id: 9,
    agency: "Bordeaux",
    quantity: 9,
  },
  {
    id: 10,
    agency: "Lille",
    quantity: 1,
  },
  {
    id: 11,
    agency: "Rennes",
    quantity: 12,
  },
  {
    id: 12,
    agency: "Grenoble",
    quantity: 9,
  },
  {
    id: 13,
    agency: "Nancy",
    quantity: 3,
  },
  {
    id: 14,
    agency: "Angers",
    quantity: 8,
  },
  {
    id: 15,
    agency: "Brest",
    quantity: 5,
  },
  {
    id: 16,
    agency: "Dijon",
    quantity: 7,
  },
];

export const products = [
  {
    id: 1,
    reference: "REF001",
    name: "Product 1",
    description: "This is product 1",
    brand: "Brand 1",
    price: 10.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 2,
    reference: "REF002",
    name: "Product 2",
    description: "This is product 2",
    brand: "Brand 2",
    price: 19.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 3,
    reference: "REF003",
    name: "Product 3",
    description: "This is product 3",
    brand: "Brand 3",
    price: 15.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 4,
    reference: "REF004",
    name: "Product 4",
    description: "This is product 4",
    brand: "Brand 4",
    price: 12.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 5,
    reference: "REF005",
    name: "Product 5",
    description: "This is product 5",
    brand: "Brand 5",
    price: 17.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 6,
    reference: "REF006",
    name: "Product 6",
    description: "This is product 6",
    brand: "Brand 6",
    price: 11.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 7,
    reference: "REF007",
    name: "Product 7",
    description: "This is product 7",
    brand: "Brand 7",
    price: 14.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 8,
    reference: "REF008",
    name: "Product 8",
    description: "This is product 8",
    brand: "Brand 8",
    price: 16.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 9,
    reference: "REF009",
    name: "Product 9",
    description: "This is product 9",
    brand: "Brand 9",
    price: 13.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 10,
    reference: "REF010",
    name: "Product 10",
    description: "This is product 10",
    brand: "Brand 10",
    price: 18.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 11,
    reference: "REF011",
    name: "Product 11",
    description: "This is product 11",
    brand: "Brand 11",
    price: 21.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 12,
    reference: "REF012",
    name: "Product 12",
    description: "This is product 12",
    brand: "Brand 12",
    price: 23.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 13,
    reference: "REF013",
    name: "Product 13",
    description: "This is product 13",
    brand: "Brand 13",
    price: 20.99,
    stocks: productStocks,
  },
  {
    id: 14,
    reference: "REF014",
    name: "Product 14",
    description: "This is product 14",
    brand: "Brand 14",
    price: 22.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 15,
    reference: "REF015",
    name: "Product 15",
    description: "This is product 15",
    brand: "Brand 15",
    price: 25.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 16,
    reference: "REF016",
    name: "Product 16",
    description: "This is product 16",
    brand: "Brand 16",
    price: 27.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 17,
    reference: "REF017",
    name: "Product 17",
    description: "This is product 17",
    brand: "Brand 17",
    price: 26.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 18,
    reference: "REF018",
    name: "Product 18",
    description: "This is product 18",
    brand: "Brand 18",
    price: 28.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 19,
    reference: "REF019",
    name: "Product 19",
    description: "This is product 19",
    brand: "Brand 19",
    price: 24.99,
    category: "Category 1",
    stocks: productStocks,
  },
  {
    id: 20,
    reference: "REF020",
    name: "Product 20",
    description: "This is product 20",
    brand: "Brand 20",
    price: 30.99,
    category: "Category 1",
    stocks: productStocks,
  },
];
