const data = [
  {
    id: 1,
    name: "Doe",
    firstname: "John",
    address: "123 Main St",
    city: "New York",
    email: "john.doe@example.com",
    avatar: "https://randomuser.me/api/portraits/men/26.jpg",
    phone: "123-456-7890",
  },
  {
    id: 2,
    name: "Smith",
    firstname: "Jane",
    address: "456 Elm St",
    city: "Los Angeles",
    email: "jane.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/women/60.jpg",
    phone: "123-456-7890",
  },
  {
    id: 3,
    name: "Williams",
    firstname: "David",
    address: "789 Oak St",
    city: "Chicago",
    email: "david.williams@example.com",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
    phone: "123-456-7890",
  },
  {
    id: 4,
    name: "Johnson",
    firstname: "Emily",
    address: "321 Pine St",
    city: "San Francisco",
    email: "emily.johnson@example.com",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    phone: "123-456-7890",
  },
  {
    id: 5,
    name: "Brown",
    firstname: "Michael",
    address: "987 Maple St",
    city: "Houston",
    email: "michael.brown@example.com",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    phone: "123-456-7890",
  },
  {
    id: 6,
    name: "Jones",
    firstname: "Olivia",
    address: "654 Cedar St",
    city: "Miami",
    email: "olivia.jones@example.com",
    avatar: "https://randomuser.me/api/portraits/women/95.jpg",
    phone: "123-456-7890",
  },
  {
    id: 7,
    name: "Miller",
    firstname: "Daniel",
    address: "321 Oak St",
    city: "Seattle",
    email: "daniel.miller@example.com",
    avatar: "https://randomuser.me/api/portraits/men/97.jpg",
    phone: "123-456-7890",
  },
  {
    id: 8,
    name: "Davis",
    firstname: "Sophia",
    address: "789 Elm St",
    city: "Dallas",
    email: "sophia.davis@example.com",
    avatar: "https://randomuser.me/api/portraits/women/49.jpg",
    phone: "123-456-7890",
  },
  {
    id: 9,
    name: "Taylor",
    firstname: "James",
    address: "987 Pine St",
    city: "Atlanta",
    email: "james.taylor@example.com",
    avatar: "https://randomuser.me/api/portraits/men/36.jpg",
    phone: "123-456-7890",
  },
  {
    id: 10,
    name: "Anderson",
    firstname: "Bill",
    address: "654 Cedar St",
    city: "Denver",
    email: "bill.anderson@example.com",
    avatar: "https://randomuser.me/api/portraits/men/79.jpg",
    phone: "123-456-7890",
  },
];

export default data;
