query GetAllProductCharacteristics($limit: Int, $offset: Int, $name: String) {
  getAllProductCharacteristics(limit: $limit, offset: $offset, name: $name) {
    productCharacteristics {
      id
      name
    }
    total
  }
}
