query GetAllProductCharacteristics($limit: Int, $offset: Int) {
  getAllProductCharacteristics(limit: $limit, offset: $offset) {
    productCharacteristics {
      id
      name
    }
    total
  }
}
