mutation UpdateProductCharacteristic($data: UpdateProductCharacteristicInput!, $productCharacteristicId: Float!) {
  updateProductCharacteristic(data: $data, productCharacteristicId: $productCharacteristicId) {
    name
  }
}
