mutation UpdateProductCharacteristic($data: UpdateProductCharacteristicInput!, $updateProductCharacteristicId: Float!) {
  updateProductCharacteristic(data: $data, id: $updateProductCharacteristicId) {
    name
  }
}
