mutation UpdateProductCharacteristic($data: UpdateProductCharacteristicInput!, $productCharacteristicId: Int!) {
  updateProductCharacteristic(data: $data, productCharacteristicId: $productCharacteristicId) {
    name
  }
}
