mutation CreateAgency($data: NewAgencyInput!) {
  createAgency(data: $data) {
    id
    name
    address
    postcode
    city
    country
    phone
    email
    bookings {
      id
    }
    productCodes {
      id
    }
  }
}