query GetAgencyById($agencyId: Int!) {
  getAgencyById(agencyId: $agencyId) {
    address
    city
    country
    email
    id
    name
    phone
    postcode
    productCodes {
      id
      bookingItems {
        endDate
        startDate
      }
      size
      product {
        id
      }
    }
  }
}