#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Project currently being analyzed👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

# Navigate to frontend directory and run lint
cd frontend && npm run lint
# Navigate back to the root directory
cd ..

# Navigate to backend directory and run lint
cd backend && npm run lint
# Navigate back to the root directory
cd ..

echo 'Success! 🎉🎉🎉'