mutation CreateProduct($data: NewProductInput!) {
  createProduct(data: $data) {
    id
    name
    price
    description
    thumbnail
    category {
      id
    }
    brand {
      id
    }
  }
}
