query getAllProductsByCategoryID($categoryId: Int) {
  getAllProducts(categoryId: $categoryId) {
    brand {
      id
      logo
      name
    }
    description
    id
    name
    price
    thumbnail
    characteristics {
      id
      name
    }
    pictures {
      alt
      id
      thumbnail
    }
    reviews {
      comment
      id
      rate
    }
    category {
      id
    }
  }
}
