query getAllProducts($sortOrder: SortProduct, $limit: Int, $offset: Int, $name: String) {
  getAllProducts(sortOrder: $sortOrder, limit: $limit, offset: $offset, name: $name) {
    products {
      id
      name
      price
      description
      thumbnail
      brand {
        id
        name
      }
      category {
        id
        name
      }
    }
    total
  }
}