  getAllProducts(sortOrder: $sortOrder, limit: $limit, offset: $offset) {
query GetAllProducts($sortOrder: SortProduct, $limit: Int, $offset: Int) {
    products {
      id
      name
      price
      description
      thumbnail
      brand {
        id
        name
      }
      category {
        id
        name
      }
    }
    total
  }
}