query GetBookingItemDatesByProductCodeId($productCodeId: Int!, $agencyId: Float) {
  getBookingItemDatesByProductCodeId(productCodeId: $productCodeId, agencyId: $agencyId) {
    startDate
    endDate
  }
}