query GetAllProducts {
  getAllProducts {
    brand {
      id
      logo
      name
    }
    description
    id
    name
    price
    thumbnail
    characteristics {
      characteristic
      id
    }
  }
}
