query GetProductsDetails {
  getAllProducts {
    products {
      brand {
        id
        logo
        name
      }
      description
      id
      name
      price
      thumbnail
      characteristics {
        characteristic
        id
      }
      pictures {
        alt
        id
        thumbnail
      }
      reviews {
        comment
        id
        rate
      }
    }
  }
}
