mutation UpdateProduct($data: UpdateProductInput!, $productId: Int!) {
  updateProduct(data: $data, productId: $productId) {
    name
    price
    description
    thumbnail
    category {
      id
    }
    brand {
      id
    }
  }
}
