name: e2e-tests

on:
  pull_request:
  workflow_call:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e-tests
    steps:
      # Docker layer caching
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - uses: actions/checkout@v4
      - name: Install Required Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff2-dev \
            libwoff2-1 \
            libglib2.0-0 \
            libnss3 \
            libgconf-2-4 \
            libfontconfig1 \
            libxss1 \
            libasound2 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxi6 \
            libxtst6 \
            fonts-liberation \
            libappindicator1 \
            libappindicator3-1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Install backend dependencies
        run: cd ../backend && npm ci

      # Create .env file using secrets
      - name: Create .env from Secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> ../backend/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> ../backend/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> ../backend/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ../backend/.env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> ../backend/.env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> ../backend/.env
          echo "JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}" >> ../backend/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> ../backend/.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> ../backend/.env
          echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}" >> ../backend/.env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> ../backend/.env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> ../backend/.env
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> ../backend/.env
          echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> ../backend/.env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> ../backend/.env

          echo "DB_HOST=${{ secrets.DB_HOST }}" >> ../e2e-tests/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> ../e2e-tests/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> ../e2e-tests/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ../e2e-tests/.env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> ../e2e-tests/.env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> ../e2e-tests/.env
          echo "JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}" >> ../e2e-tests/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> ../e2e-tests/.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> ../e2e-tests/.env
          echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}" >> ../e2e-tests/.env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> ../e2e-tests/.env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> ../e2e-tests/.env
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> ../e2e-tests/.env
          echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> ../e2e-tests/.env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> ../e2e-tests/.env

          echo "JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}" >> ../frontend/.env
          echo "NEXT_PUBLIC_GRAPHQL_API_URL=${{ secrets.NEXT_PUBLIC_GRAPHQL_API_URL }}" >> ../frontend/.env
          echo "NEXT_PUBLIC_UPLOAD_API_ENDPOINT=${{ secrets.NEXT_PUBLIC_UPLOAD_API_ENDPOINT }}" >> ../frontend/.env

      # Store Playwright's Version
      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      # Cache Playwright Browsers for Playwright's Version
      - name: Cache Playwright Browsers
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      # Setup Playwright if not cached
      - name: Setup Playwright
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      # Start your application using the .env file
      - name: Start app
        run: |
          npm run app:start & sleep 120

      # Run Playwright tests
      - name: Run Playwright tests
        run: npm run test

      # Store Artifacts from Failed Tests
      - name: Store Artifacts from Failed Tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: e2e-tests/test-results/
          retention-days: 7
