name: "integration-tests"

on:
  pull_request:
  workflow_call:

jobs:
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Create .env file using secrets
      - name: Create .env from Secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> ../backend/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> ../backend/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> ../backend/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ../backend/.env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> ../backend/.env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> ../backend/.env
          echo "JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}" >> ../backend/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> ../backend/.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> ../backend/.env
          echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}" >> ../backend/.env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> ../backend/.env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> ../backend/.env
          echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> ../backend/.env
          echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> ../backend/.env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> ../backend/.env

      - name: Install deps
        run: npm ci

      - name: Start test DB
        run: npm run testDB:wait

      - name: Run tests
        run: npm test
