name: "prettier"

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_call:

jobs:
  prettier-backend:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    if: contains(github.event.head_commit.message, 'backend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies for backend
        run: npm ci

      - name: Run Prettier fix on backend
        run: npm run prettier:fix

      - name: Commit changes if necessary
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: apply prettier fixes [skip ci]"

      - name: Push changes
        if: github.event_name == 'push'
        run: |
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prettier-frontend:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    if: contains(github.event.head_commit.message, 'frontend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies for frontend
        run: npm ci

      - name: Run Prettier fix on frontend
        run: npm run prettier:fix

      - name: Commit changes if necessary
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: apply prettier fixes [skip ci]"

      - name: Push changes (only on push events, not pull requests)
        if: github.event_name == 'push'
        run: |
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
